In [1]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 
from sklearn.model_selection import train_test_split 
from sklearn.preprocessing import StandardScaler

In [2]:
dataset = pd.read_csv('dataset.csv') 
dataset.head()


0x  0y        1x        1y        2x        2y        3x        3y  \
0   0   0  0.123872 -0.017960  0.219229 -0.068171  0.312341 -0.105117   
1   0   0  0.122147 -0.020746  0.215053 -0.071974  0.312275 -0.105592   
2   0   0  0.117563 -0.022413  0.215767 -0.073250  0.309503 -0.107768   
3   0   0  0.123284 -0.017237  0.222560 -0.068265  0.326233 -0.099741   
4   0   0  0.110718 -0.012560  0.207945 -0.060300  0.303405 -0.093189   

         4x        4y  ...   0_14   0_15   0_16   0_17   0_18   0_19   0_20  \
0  0.365503 -0.152174  ...  0.289  0.357  0.416  0.173  0.260  0.315  0.366   
1  0.370285 -0.153577  ...  0.295  0.363  0.421  0.171  0.262  0.318  0.370   
2  0.358946 -0.155869  ...  0.306  0.372  0.429  0.176  0.272  0.326  0.376   
3  0.397841 -0.146186  ...  0.293  0.368  0.431  0.148  0.223  0.274  0.318   
4  0.362125 -0.136103  ...  0.278  0.347  0.407  0.146  0.227  0.277  0.323   

   Handedness  Label        Location  
0      Left\r      0    0/frame0.jpg  
1      Left\r      0    0/frame1.jpg  
2      Left\r      0   0/frame10.jpg  
3      Left\r      0  0/frame100.jpg  
4      Left\r      0  0/frame101.jpg  

[5 rows x 65 columns]

In [3]:
dataset.info()
dataset.columns

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16070 entries, 0 to 16069
Data columns (total 65 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   0x          16070 non-null  int64  
 1   0y          16070 non-null  int64  
 2   1x          16070 non-null  float64
 3   1y          16070 non-null  float64
 4   2x          16070 non-null  float64
 5   2y          16070 non-null  float64
 6   3x          16070 non-null  float64
 7   3y          16070 non-null  float64
 8   4x          16070 non-null  float64
 9   4y          16070 non-null  float64
 10  5x          16070 non-null  float64
 11  5y          16070 non-null  float64
 12  6x          16070 non-null  float64
 13  6y          16070 non-null  float64
 14  7x          16070 non-null  float64
 15  7y          16070 non-null  float64
 16  8x          16070 non-null  float64
 17  8y          16070 non-null  float64
 18  9x          16070 non-null  float64
 19  9y          16070 non-nul

Index(['0x', '0y', '1x', '1y', '2x', '2y', '3x', '3y', '4x', '4y', '5x', '5y',
       '6x', '6y', '7x', '7y', '8x', '8y', '9x', '9y', '10x', '10y', '11x',
       '11y', '12x', '12y', '13x', '13y', '14x', '14y', '15x', '15y', '16x',
       '16y', '17x', '17y', '18x', '18y', '19x', '19y', '20x', '20y', '0_1',
       '0_2', '0_3', '0_4', '0_5', '0_6', '0_7', '0_8', '0_9', '0_10', '0_11',
       '0_12', '0_13', '0_14', '0_15', '0_16', '0_17', '0_18', '0_19', '0_20',
       'Handedness', 'Label', 'Location'],
      dtype='object')

In [4]:
dataset["Handedness"].value_counts()

Right\r    8323
Left\r     7747
Name: Handedness, dtype: int64

In [5]:
dataset["Handedness"] = np.where(dataset["Handedness"].str.contains("right"), 1, 0)
dataset.head()

0x  0y        1x        1y        2x        2y        3x        3y  \
0   0   0  0.123872 -0.017960  0.219229 -0.068171  0.312341 -0.105117   
1   0   0  0.122147 -0.020746  0.215053 -0.071974  0.312275 -0.105592   
2   0   0  0.117563 -0.022413  0.215767 -0.073250  0.309503 -0.107768   
3   0   0  0.123284 -0.017237  0.222560 -0.068265  0.326233 -0.099741   
4   0   0  0.110718 -0.012560  0.207945 -0.060300  0.303405 -0.093189   

         4x        4y  ...   0_14   0_15   0_16   0_17   0_18   0_19   0_20  \
0  0.365503 -0.152174  ...  0.289  0.357  0.416  0.173  0.260  0.315  0.366   
1  0.370285 -0.153577  ...  0.295  0.363  0.421  0.171  0.262  0.318  0.370   
2  0.358946 -0.155869  ...  0.306  0.372  0.429  0.176  0.272  0.326  0.376   
3  0.397841 -0.146186  ...  0.293  0.368  0.431  0.148  0.223  0.274  0.318   
4  0.362125 -0.136103  ...  0.278  0.347  0.407  0.146  0.227  0.277  0.323   

   Handedness  Label        Location  
0           0      0    0/frame0.jpg  
1           0      0    0/frame1.jpg  
2           0      0   0/frame10.jpg  
3           0      0  0/frame100.jpg  
4           0      0  0/frame101.jpg  

[5 rows x 65 columns]

In [29]:
print(dataset.std(axis=0)[42:61])

0_1     0.027570
0_2     0.049779
0_3     0.077053
0_4     0.100788
0_5     0.042263
0_6     0.062024
0_7     0.092061
0_8     0.128960
0_9     0.039630
0_10    0.063593
0_11    0.106578
0_12    0.147073
0_13    0.041183
0_14    0.061954
0_15    0.100891
0_16    0.137336
0_17    0.047146
0_18    0.062404
0_19    0.089574
dtype: float64


In [6]:
# input 
x = np.array(dataset.drop(["0x","0y","Label","Location"],axis=1))
x

array([[ 0.12387231, -0.01796007,  0.21922916, ...,  0.315     ,
         0.366     ,  0.        ],
       [ 0.12214667, -0.02074552,  0.21505275, ...,  0.318     ,
         0.37      ,  0.        ],
       [ 0.11756349, -0.02241278,  0.21576661, ...,  0.326     ,
         0.376     ,  0.        ],
       ...,
       [ 0.07603985, -0.00732273,  0.11780751, ...,  0.068     ,
         0.058     ,  0.        ],
       [ 0.08211881, -0.03339344,  0.10400295, ...,  0.119     ,
         0.092     ,  0.        ],
       [ 0.09794569,  0.0032872 ,  0.14370072, ...,  0.087     ,
         0.066     ,  0.        ]])

In [7]:

print(np.all(np.isfinite(x)))
print(x[:,0].shape)
index = 0
for i in x[:,0]:
    if not np.isfinite(i):
        print(index, i)
    index +=1

True
(16070,)


In [8]:
# output 
y = dataset.drop("Location",axis=1).iloc[:, -1].values
y

array(['0', '0', '0', ..., 'Z', 'Z', 'Z'], dtype=object)

In [9]:
xtrain, xtest, ytrain, ytest = train_test_split(x, y, test_size = 0.30, random_state = 5)

In [10]:
print(xtrain[29])
print(ytrain[29])

[-0.17868617 -0.02407348 -0.30363719 -0.13749787 -0.34227632 -0.24685091
 -0.36865084 -0.33354887 -0.23306626 -0.23124591 -0.25014032 -0.30477238
 -0.21477637 -0.22324413 -0.19137442 -0.17790347 -0.1157833  -0.23283348
 -0.1265479  -0.29849273 -0.10852817 -0.18342882 -0.0958603  -0.1554611
  0.00340843 -0.21981174 -0.0047124  -0.2752206  -0.01293656 -0.164579
 -0.00406638 -0.13850638  0.11765331 -0.19424564  0.11269933 -0.22464821
  0.08572966 -0.15014261  0.08115023 -0.13495952  0.18        0.333
  0.422       0.497       0.328       0.394       0.31        0.261
  0.26        0.324       0.213       0.183       0.22        0.275
  0.165       0.139       0.227       0.251       0.173       0.157
  0.        ]
A


In [60]:
# sc_x = StandardScaler() 
# xtrain = sc_x.fit_transform(xtrain)  
# xtest = sc_x.transform(xtest) 
  
# print (xtrain[0:10, :]) 
# print(ytrain[0:10])

In [11]:
from sklearn.linear_model import LogisticRegression 
classifier = LogisticRegression(random_state = 0) 
classifier.fit(xtrain, ytrain) 

LogisticRegression(random_state=0)

In [12]:
y_pred = classifier.predict(xtest) 

In [13]:
from sklearn.metrics import confusion_matrix 
cm = confusion_matrix(ytest, y_pred) 
  
print ("Confusion Matrix : \n", cm)

Confusion Matrix : 
 [[121   0   0 ...   0   0   0]
 [  0 109   0 ...   0   0   0]
 [  0   0 160 ...   0   0   0]
 ...
 [  0   0   0 ... 110   0   0]
 [  0   0   0 ...   0 179   0]
 [  0   1   0 ...   2   0  48]]


In [14]:
from sklearn.metrics import accuracy_score 
print ("Accuracy : ", accuracy_score(ytest, y_pred)) 

Accuracy :  0.9332088778261771


In [16]:
from sklearn.tree import DecisionTreeClassifier

dtree = DecisionTreeClassifier(max_depth=100,max_features=None)
dtree.fit(xtrain,ytrain)
y_pred1 = dtree.predict(xtest)

In [17]:
print ("Accuracy : ", accuracy_score(ytest, y_pred1)) 

Accuracy :  0.9668118647583489


In [18]:
from sklearn.ensemble import RandomForestClassifier

rfm = RandomForestClassifier(n_estimators=100,max_features=None,n_jobs=10)
rfm.fit(xtrain,ytrain)
y_pred2 = rfm.predict(xtest)
print ("Accuracy : ", accuracy_score(ytest, y_pred2))

Accuracy :  0.9896287077369841


In [19]:
from sklearn.svm import SVC

svm = SVC(kernel="linear",C=0.025,random_state=101)
svm.fit(xtrain,ytrain)
y_pred3 = svm.predict(xtest)
print ("Accuracy : ", accuracy_score(ytest, y_pred3)) 

Accuracy :  0.5339141257000622


In [20]:
import joblib
# save
joblib.dump(classifier, "logistic.joblib")
joblib.dump(rfm, "random_forest.joblib")


['random_forest.joblib']

In [35]:
ytest[:100]

array(['I', 'A', 'N', 'N', 'I', 'F', 'X', '2', 'R', 'E', '9', 'X', 'A',
       'A', '4', 'N', 'W', '8', 'T', 'Y', 'E', 'E', '0', '8', 'J', '7',
       '6', 'C', 'Y', 'Y', 'Y', 'F', '2', 'D', 'N', 'A', '9', '5', '3',
       'V', '1', 'M', 'X', 'D', 'L', '7', 'O', 'X', '2', '9', '2', 'H',
       'H', '9', 'Q', 'O', 'V', 'M', '6', '3', 'X', 'E', 'T', 'I', 'V',
       'T', 'L', '4', '2', 'V', '3', 'G', 'B', '0', 'Y', 'N', 'U', 'G',
       '4', 'A', 'R', 'J', '3', 'V', 'M', 'J', 'B', 'X', 'Q', 'S', 'L',
       '2', 'I', 'A', 'V', 'L', 'K', 'W', 'R', 'E'], dtype=object)

In [36]:
y_pred2[:100]

array(['I', 'A', 'N', 'N', 'I', 'F', 'X', '2', 'R', 'E', '9', 'X', 'A',
       'A', '4', 'N', 'W', '8', 'T', 'Y', 'E', 'E', '0', '8', 'J', '7',
       '6', 'C', 'Y', 'Y', 'Y', 'F', '2', 'D', 'N', 'A', '9', '5', '3',
       'V', '1', 'M', 'X', 'D', 'L', '7', 'O', 'X', '2', '9', '2', 'H',
       'H', '9', 'Q', 'O', 'V', 'M', '6', '3', 'X', 'E', 'T', 'I', 'V',
       'T', 'L', '4', '2', 'V', '3', 'G', 'B', '0', 'Y', 'N', 'U', 'G',
       '4', 'A', 'R', 'J', '3', 'V', 'M', 'J', 'B', 'X', 'Q', 'S', 'L',
       '2', 'I', 'A', 'V', 'L', 'K', 'W', 'R', 'E'], dtype=object)

In [66]:
xtest[12]

array([ 1.18056388, -0.56972325,  1.24035657, -0.84371615,  1.22846497,
       -1.00177947,  1.06214875, -0.99079317,  1.19873505, -0.27015928,
        1.19497335, -0.16607875,  0.97749719,  0.5568105 ,  0.78064328,
        0.65802475,  0.80282232, -0.16641324,  0.87771838, -0.05663556,
        0.75342639,  0.58562703,  0.51851612,  0.55824704, -0.02003498,
       -0.2246671 ,  0.32017267, -0.21196209,  0.37394675,  0.27920114,
        0.12468843,  0.19939825, -0.61560351, -0.31907687, -0.17964981,
       -0.22513353, -0.06358883,  0.17372845, -0.27925798,  0.11599051,
        0.46494448,  0.71763534,  0.73153004,  0.4219576 ,  0.12391176,
        0.07117936, -0.87204494, -1.04740635, -0.35590495, -0.42118929,
       -0.99093766, -0.9513661 , -0.53358086, -0.51135235, -0.73625397,
       -0.5501979 , -0.34717238, -0.70506209, -0.80900867, -0.5137729 ,
        0.        ])

In [67]:
ytest[12]

'A'